### ISSUE TITLE
when multiple selection, only applies to the first one

### ISSUE THREAD

**Issue by huafu** [jeff-hykin/selection-convert#1]
First of all, thanks for this extension.
Anyway, I'm trying to use on multiple selection, and it works only for the first selected item.

**Comment by jeff-hykin** [comment]
Ah, I'd like that fixed as well. Might take me a couple weeks to get around to it but I'll see what I can do

**Comment by jeff-hykin** [comment]
should be fixed in `v0.0.3`!
